format = "$all"

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)@"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "[$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

[status]
map_symbol = true
disabled = false

[shell]
disabled = false
